## NumPy Lec Notes
Video link: https://www.youtube.com/watch?v=VXU4LSAQDSc

This is the Notebook I use to learn NumPy from the given video above. This ipynb contains the examples as well as the notes.

In [13]:
import numpy as np

# print(np.__version__) ## NumPy version check

array1 = [1,2,3,4] ## Standard Python array
array2 = np.array([1,2,3,4]) ## NumPy Array

## Multiplying array's by 2
print(array1*2)
print(array2*2)

## Printing both array types
print(type(array1))
print(type(array2))

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
<class 'list'>
<class 'numpy.ndarray'>


#### Multidimensional Array
- We use the `array.ndim` to get the dimensions of our array
- We use `array.shape` to know to know the size of the array in each dimension
##### Indexing
1. **Chain Indexing**: `array[][]` - This type of indexing where you mention each element in separate square bracket is called a chain indexing.
2. **Multidimensional Indexing**: `array[0,0,0]` - Separating the indices by commas

In [11]:
array1 = np.array("N") ## Zero dimensional array, aka constant
array2 = np.array([1,2,3,4]) ## One dimensional array, aka vector
array3 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]]) ## Two dimensional array, aka matrix

print(array1.ndim, array2.ndim, array3.ndim) ## ndim is used to find the dimensions of the given array
print(array1.shape, array2.shape, array3.shape) ## shape is used to give the size of each dimension
print(array3[1][2], array3[2,1]) ## Chain vs MultiDim Indexing

array3[1][2] = 4

print(array3[1], array3[2,1]) ## Chain vs MultiDim Indexing
print(array3)

0 1 2
() (4,) (3, 3)
6 8
[4 5 4] 8
[[1 2 3]
 [4 5 4]
 [7 8 9]]


In [10]:
n = 4
m = 3
zero_matrix = np.zeros((n, m), dtype=int)
print(zero_matrix)

3


In [18]:
x = [1,[7,8],2,"efgh",[3,4]] # Statement 1
y = x[0:50] # Statement 2
z = y # Statement 3
w = x # Statement 4
x[1] = "abcd" # Statement 5
y[1][1] = "y" # Statement 6
w[1][1] = "9" # Statement 7
y[2] = 4 # Statement 8
z[0] = 0 # Statement 9
w[4][0] = 1000 # Statement 10

TypeError: 'str' object does not support item assignment

In [17]:
for i in range(6,3,-1):
    print(i)

6
5
4


In [20]:
def f(l):
    l = l + [l[0]]
    return(l)

def g(l):
    l.append(l[0])
    return(l)

list1 = [4,3,9,7]  # 4,3,9,7,4
list2 = g(list1)   # 4,3,9,7,4
list3 = f(list2)   # 4,3,9,7,4,4

print(list1)
print(list2)
print(list3)

[4, 3, 9, 7, 4]
[4, 3, 9, 7, 4]
[4, 3, 9, 7, 4, 4]


TypeError: '>' not supported between instances of 'int' and 'NoneType'